### ISSUE TITLE
Lima had a minor earthquake

### ISSUE THREAD

**Issue by AngryKnees** [RussStation/RussStation#110]
## Description:
#109 Updated the codebase without syncing Lima to those changes.
The relevant runtimes are logged below
[runtime.log](https://github.com/RussStation/RussStation/files/4216940/runtime.log)

## Reproduction:
1. Boot the server with the map as Lima
2. Look at the runtimes
3. Hold in the tears

**Comment by danxensen** [comment]
pretty sure this has been fixed for quite a while
