### ISSUE TITLE
Confetti slips

### ISSUE THREAD

**Issue by flufflycthu1u** [RussStation/RussStation#118]
Inspired by famencio's admemes.

![image](https://user-images.githubusercontent.com/2520037/75741414-827ad200-5cd8-11ea-83c6-0dd3324e4f82.png)

A banana peel which upon slipping someone makes a burst of confetti like the clown's farts.
My preferred solution for this would be to create a ~subtype of the slippery~ spawn on step component which spawns an object specified in a var to allow further memes. I'd also like a var to set the number of uses.

The code for the slippery component can be found here:
https://github.com/RussStation/RussStation/blob/master/code/datums/components/slippery.dm

**Comment by unv-annihilator** [comment]
Started on this, made it into a new plant for the time being so has no icons. 
Should be able to be added to any plant?

WIP Example: https://i.imgur.com/xPi5exH.mp4

Fork Branch: https://github.com/unv-annihilator/RussStation/tree/banana-confetti

**Comment by cakexensen** [comment]
implemented in #296
