### ISSUE TITLE
Shot-gun

### ISSUE THREAD

**Issue by AngryKnees** [RussStation/RussStation#18]
> idea, we rip off Always Sunny in Philly and make the SHOT-GUN for the bartender.  Fires 5 units of beer into people's mouth.  Emag to load beakers. - Russ 2k19

**Comment by AngryKnees** [comment]
Personally I think that 5u is rather conservative, but that can be easily tested.

**Comment by AngryKnees** [comment]
https://www.youtube.com/watch?v=eD7dGTt96uY

**Comment by danxensen** [comment]
Implemented in #141
