### ISSUE TITLE
Missing disposal pipe in medbay

### ISSUE THREAD

**Issue by Fishduke25** [RussStation/RussStation#204]
There is a missing disposal pipe on tile in front of the nanodrug near the pharmacy
![image](https://user-images.githubusercontent.com/87911586/126877724-e7bcb453-9630-4ca5-8566-0bb292d8c55c.png)
I moved the wire and atmos pipes to make it clearer

**Comment by danxensen** [comment]
i think this was fixed but then we redid medbay recently so this is definitely no longer an issue
