### ISSUE TITLE
can't make wet hide easily

### ISSUE THREAD

**Issue by cakexensen** [RussStation/RussStation#249]
## Description:
using hide on a water source doesn't make it into wet hide, forced to throw water at it

## Reproduction:

skin animal, scrape the hide, use it on puddle, cry

**Comment by SushiFish100** [comment]
gotta get water into a bucket and right click the hide with the bucket selected to make wet hide, unless the new area doesnt give you buckets or something

**Comment by cakexensen** [comment]
thanks, updated wiki to reflect this for anyone else that gets confused
