### ISSUE TITLE
Yuno Cards

### ISSUE THREAD

**Issue by AngryKnees** [RussStation/RussStation#37]
# Yuno Cards

Add `/obj/item/toy/cards/deck/yuno`. It should behave the same as a deck of cards but instead of containing face cards, it should contain ~Uno~ Yuno cards. 

### But y tho
Because Uno is fun and simple, and normal cards require too many brain cells. Get dicked down by a moth person with a Draw 4 card.

**Comment by cakexensen** [comment]
upstream already implemented this
