### ISSUE TITLE
SCP-529 "Josie"

### ISSUE THREAD

**Issue by flufflycthu1u** [RussStation/RussStation#46]
## Description:
SCP-529 isn't inheriting from the cat simple_mob type, doesn't have icons, and the file is in the wrong location.
To fix the inheritance the definition needs to be changed to include pet for `/mob/living/simple_animal/pet/cat/SCP529`
The icons can be fixed one of two ways, either set the icon states to `cat` and `cat_dead` or in the dmi double click on the icon names and replace cat with josie in all cases.
Finally the file location should be `russstation/code/modules/mob/living/simple_animal/friendly/cat.dm` rather than `russstation/code/modules/mob/cat.dm`.

## Reproduction:
Spawn SCP529 on a local test server and it doesn't have any icons or the proper functions.

**Comment by AngryKnees** [comment]
fixed in #47
