### ISSUE TITLE
Virus that does not contain hallucinations has hallucinations as a hidden symptom

### ISSUE THREAD

**Issue by jzburda** [RussStation/RussStation#51]
## Description:

I have a Virus with /Sneezing/Self Respiration/Regenerative Coma/Eternal Youth and Headache and it seems to also have Hallucinogen on it
## Reproduction:

Create a virus with /Sneezing/Self Respiration/Regenerative Coma/Eternal Youth and Headache and the virus will also have Hallucinogen.

**Comment by AngryKnees** [comment]
We haven't touched the virus code in this downstream repo, and therefore we aren't maintaining it. That being said I'd recommend opening this issue up on the tg repo
https://github.com/tgstation/tgstation/issues
